Add 0-list_databases script

diff --git a/NoSQL/0-list_databases b/NoSQL/0-list_databases
--- a/NoSQL/0-list_databases
+++ b/NoSQL/0-list_databases
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 if command -v mongosh &> /dev/null; then
-    echo "show dbs" | mongosh --quiet
-else
+    mongosh --quiet --eval "db.adminCommand('listDatabases')"
+elif command -v mongo &> /dev/null; then
     echo "show dbs" | mongo --quiet
+else
+    echo "MongoDB client not found"
+    exit 1
 fi
